!------------------------------------------------------------------------------
! This are the parameters for the Courte Model
! Constants
!------------------------------------------------------------------------------
! Model Constants
!
 real(rp), parameter, private :: p_R        = 8.3143;  
 real(rp), parameter, private :: p_FA       = 96.4867;
 real(rp), parameter, private :: p_Te       = 310.0;      
 real(rp), parameter, private :: p_voli     = 13668.0;   
 real(rp), parameter, private :: p_volrel   = 96.48;
 real(rp), parameter, private :: p_volup    = 1109.52;

 real(rp), parameter, private :: p_gna      = 7.8;       
 real(rp), parameter, private :: p_gk1      = 0.09;       
 real(rp), parameter, private :: p_gto      = 0.1652;       
 real(rp), parameter, private :: p_gkr      = 0.029411765;       
 real(rp), parameter, private :: p_gks      = 0.12941176;       
 real(rp), parameter, private :: p_gcal     = 0.12375;  
 real(rp), parameter, private :: p_gach     = 1.0;     
 real(rp), parameter, private :: p_inakm    = 0.59933874;
 real(rp), parameter, private :: p_inacam   = 1600.0;       
 real(rp), parameter, private :: p_gbca     = 0.001131;
 real(rp), parameter, private :: p_gbna     = 0.0006744375;              
 real(rp), parameter, private :: p_ipcam    = 0.275;
 real(rp), parameter, private :: p_krel     = 30.0;       
 real(rp), parameter, private :: p_iupm     = 0.005;   
 real(rp), parameter, private :: p_taufca   = 2.0;
 real(rp), parameter, private :: p_kmnai    = 10.0;
 real(rp), parameter, private :: p_kmko     = 1.5;
 real(rp), parameter, private :: p_kmna     = 87.5;
 real(rp), parameter, private :: p_kmca     = 1.38;
 real(rp), parameter, private :: p_tauu     = 8.0;
 real(rp), parameter, private :: p_tautr    = 180.0;
 real(rp), parameter, private :: p_kup      = 0.00092;
 real(rp), parameter, private :: p_caupm    = 15.0;
 real(rp), parameter, private :: p_kmcmdn   = 0.00238;
 real(rp), parameter, private :: p_kmtrpn   = 0.0005; 
 real(rp), parameter, private :: p_kmcsqn   = 0.8; 
 real(rp), parameter, private :: p_cmdnm    = 0.05;
 real(rp), parameter, private :: p_trpnm    = 0.07;
 real(rp), parameter, private :: p_csqnm    = 10.0;
 real(rp), parameter, private :: p_nao      = 140.0;
 real(rp), parameter, private :: p_ko       = 5.4;
 real(rp), parameter, private :: p_cao      = 1.8;
 real(rp), parameter, private :: p_ACh      = 0.005;

